services:
  app:
    build:
      context: .
    ports:
      - ":5000"
    volumes:
      - "./.aws:/root/.aws:ro"

  nginx: # 웹서버(리버스 프록시)
    build:
      context: .
      dockerfile: Dockerfile.nginx # NginX 설정 파일이 포함된 Dockerfile
    depends_on:
      - app # app 서비스가 준비되면 -> nginx 시작
    ports:
      - "80:80"
# Dockerfile과 docker-compose의 차이는 무엇일까욥!?
# - 빌드용 파일과 배포용 파일
# - 이미지를 생성하는것과 생성한걸로 배포하는

# Dockerfile: 단일 컨테이너 이미지 생성
# > docker build -t fastapi-app .

# docker-compose: 여러 개의 컨테이너 이미지 생성
# - 여러 개의 컨테이너
#   - app, nginx, db, nosql ....
# - 여러 개의 컨테이너 관리 (=> 쿠버네티스)
# - 무중단배포 // 도커하나만 => 도커 내리잖아요.
# => 서버가 멈춥니다. // 쿠버네티스(도커가 뒤지면 교체해주고, 다시 실행시켜주고)
# - 새로 빌드한 도커있으면 교체해주고.
